language: ruby
cache: bundler
branches:
  only:
    - master
sudo: false
dist: trusty
bundler_args: --jobs=3 --retry=3
env:
  - DB=postgresql
script:
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rake test
before_script:
  - bundle exec rake db:create RAILS_ENV=test
