language: ruby
cache: bundler
branches:
  only:
    - master
sudo: false
bundler_args: --jobs=3 --retry=3
script:
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rake test
